#!/usr/bin/env python3
"""Convert a 250x122 PNG into an Inky:bit MakeCode RLE renderer."""

from __future__ import annotations

import argparse
import struct
import zlib
from pathlib import Path


WIDTH = 250
HEIGHT = 122


def paeth(left: int, above: int, upper_left: int) -> int:
    estimate = left + above - upper_left
    left_dist = abs(estimate - left)
    above_dist = abs(estimate - above)
    upper_left_dist = abs(estimate - upper_left)
    if left_dist <= above_dist and left_dist <= upper_left_dist:
        return left
    if above_dist <= upper_left_dist:
        return above
    return upper_left


def unfilter_scanlines(data: bytes, width: int, height: int, channels: int) -> bytearray:
    stride = width * channels
    output = bytearray(height * stride)
    source = 0

    for y in range(height):
        filter_type = data[source]
        source += 1
        row = bytearray(data[source:source + stride])
        source += stride
        previous_start = (y - 1) * stride

        for x in range(stride):
            left = row[x - channels] if x >= channels else 0
            above = output[previous_start + x] if y > 0 else 0
            upper_left = output[previous_start + x - channels] if y > 0 and x >= channels else 0

            if filter_type == 1:
                row[x] = (row[x] + left) & 0xFF
            elif filter_type == 2:
                row[x] = (row[x] + above) & 0xFF
            elif filter_type == 3:
                row[x] = (row[x] + ((left + above) // 2)) & 0xFF
            elif filter_type == 4:
                row[x] = (row[x] + paeth(left, above, upper_left)) & 0xFF
            elif filter_type != 0:
                raise ValueError(f"unsupported PNG filter: {filter_type}")

        output[y * stride:(y + 1) * stride] = row

    return output


def read_png_pixels(path: Path) -> tuple[int, int, int, bytearray]:
    data = path.read_bytes()
    if not data.startswith(b"\x89PNG\r\n\x1a\n"):
        raise ValueError("not a PNG file")

    offset = 8
    width = height = bit_depth = color_type = None
    compressed = bytearray()

    while offset < len(data):
        size = struct.unpack(">I", data[offset:offset + 4])[0]
        kind = data[offset + 4:offset + 8]
        chunk = data[offset + 8:offset + 8 + size]
        offset += 12 + size

        if kind == b"IHDR":
            width, height, bit_depth, color_type, compression, filter_method, interlace = struct.unpack(
                ">IIBBBBB", chunk
            )
            if compression != 0 or filter_method != 0 or interlace != 0:
                raise ValueError("unsupported PNG compression/filter/interlace")
        elif kind == b"IDAT":
            compressed.extend(chunk)
        elif kind == b"IEND":
            break

    if width is None or height is None or bit_depth != 8:
        raise ValueError("only 8-bit PNG input is supported")
    if color_type == 6:
        channels = 4
    elif color_type == 2:
        channels = 3
    else:
        raise ValueError(f"unsupported PNG colour type: {color_type}")

    raw = unfilter_scanlines(zlib.decompress(bytes(compressed)), width, height, channels)
    return width, height, channels, raw


def palette_codes(width: int, height: int, channels: int, raw: bytearray, threshold: int) -> list[int]:
    values: list[int] = []
    stride = width * channels
    for y in range(height):
        row = y * stride
        for x in range(width):
            index = row + x * channels
            r = raw[index]
            g = raw[index + 1]
            b = raw[index + 2]
            a = raw[index + 3] if channels == 4 else 255
            gray = (r * 299 + g * 587 + b * 114) // 1000
            if a < 32 or gray >= threshold:
                values.append(0)
            else:
                values.append(1)
    return values


def rle_encode(pixels: list[int]) -> list[int]:
    encoded: list[int] = []
    current = pixels[0]
    count = 0
    for value in pixels:
        if value == current and count < 255:
            count += 1
            continue
        encoded.extend((count, current))
        current = value
        count = 1
    encoded.extend((count, current))
    return encoded


def format_hex(values: list[int]) -> str:
    return "".join(f"{value:02x}" for value in values)


def makecode_ts(encoded: list[int], source_png: Path) -> str:
    return f"""// Generated by make_png_rle.py from {source_png.name}.
// Palette: 0=white, 1=black, 2=red/accent.

const WIDTH = {WIDTH}
const HEIGHT = {HEIGHT}

const IMAGE_RLE_HEX = "{format_hex(encoded)}"

function hexNibble(index: number): number {{
    const code = IMAGE_RLE_HEX.charCodeAt(index)
    if (code >= 48 && code <= 57) {{
        return code - 48
    }}
    return code - 87
}}

function hexByte(index: number): number {{
    return hexNibble(index) * 16 + hexNibble(index + 1)
}}

function drawRleImage() {{
    let position = 0
    let index = 0

    while (index < IMAGE_RLE_HEX.length) {{
        const count = hexByte(index)
        const colour = hexByte(index + 2)

        if (colour != 0) {{
            let ink = inkybit.Color.Black
            if (colour == 2) {{
                ink = inkybit.Color.Accent
            }}

            for (let offset = 0; offset < count; offset++) {{
                const pixel = position + offset
                inkybit.setPixel(pixel % WIDTH, Math.idiv(pixel, WIDTH), ink)
            }}
        }}

        position += count
        index += 4
    }}
}}

inkybit.clear()
drawRleImage()
inkybit.show()
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("--ts", type=Path, default=Path("makecode_project/main.ts"))
    parser.add_argument("--threshold", type=int, default=210)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    width, height, channels, raw = read_png_pixels(args.input)
    if width != WIDTH or height != HEIGHT:
        raise ValueError(f"input must be {WIDTH}x{HEIGHT}; got {width}x{height}")

    pixels = palette_codes(width, height, channels, raw, args.threshold)
    encoded = rle_encode(pixels)
    args.ts.write_text(makecode_ts(encoded, args.input), encoding="utf-8")

    raw_pixels = WIDTH * HEIGHT
    print(f"PNG: {args.input}")
    print(f"MakeCode TS: {args.ts}")
    print(f"black pixels: {sum(1 for pixel in pixels if pixel == 1)}")
    print(f"RLE pairs: {len(encoded) // 2}")
    print(f"RLE values: {len(encoded)} ({len(encoded) / raw_pixels:.1%} of raw pixels)")


if __name__ == "__main__":
    main()
