#!/usr/bin/env python3
"""Create a simple PNG and a MakeCode RLE renderer for Inky:bit."""

from __future__ import annotations

import argparse
import struct
import zlib
from pathlib import Path


WIDTH = 250
HEIGHT = 122
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)


def make_pixels(diameter: int) -> list[int]:
    center_x = WIDTH // 2
    center_y = HEIGHT // 2
    radius = diameter // 2
    radius_sq = radius * radius
    pixels: list[int] = []

    for y in range(HEIGHT):
        for x in range(WIDTH):
            dx = x - center_x
            dy = y - center_y
            pixels.append(1 if dx * dx + dy * dy <= radius_sq else 0)

    return pixels


def rgb_for_code(code: int) -> tuple[int, int, int]:
    if code == 0:
        return WHITE
    if code == 1:
        return BLACK
    if code == 2:
        return RED
    raise ValueError(f"unknown palette code: {code}")


def png_chunk(kind: bytes, data: bytes) -> bytes:
    checksum = zlib.crc32(kind)
    checksum = zlib.crc32(data, checksum) & 0xFFFFFFFF
    return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", checksum)


def write_png(path: Path, pixels: list[int]) -> None:
    raw = bytearray()
    for y in range(HEIGHT):
        raw.append(0)  # PNG filter type: None
        start = y * WIDTH
        for code in pixels[start:start + WIDTH]:
            raw.extend(rgb_for_code(code))

    ihdr = struct.pack(">IIBBBBB", WIDTH, HEIGHT, 8, 2, 0, 0, 0)
    data = b"\x89PNG\r\n\x1a\n"
    data += png_chunk(b"IHDR", ihdr)
    data += png_chunk(b"IDAT", zlib.compress(bytes(raw), level=9))
    data += png_chunk(b"IEND", b"")
    path.write_bytes(data)


def rle_encode(pixels: list[int]) -> list[int]:
    encoded: list[int] = []
    current = pixels[0]
    count = 0

    for value in pixels:
        if value == current and count < 255:
            count += 1
            continue
        encoded.extend((count, current))
        current = value
        count = 1

    encoded.extend((count, current))
    return encoded


def format_values(values: list[int], values_per_line: int = 24) -> str:
    lines = []
    for index in range(0, len(values), values_per_line):
        chunk = ", ".join(str(value) for value in values[index:index + values_per_line])
        lines.append("    " + chunk + ",")
    return "\n".join(lines)


def makecode_ts(encoded: list[int], source_png: Path) -> str:
    return f"""// Generated by make_circle_png_rle.py from {source_png.name}.
// Palette: 0=white, 1=black, 2=red/accent.

const WIDTH = {WIDTH}
const HEIGHT = {HEIGHT}

const IMAGE_RLE = [
{format_values(encoded)}
]

function drawRleImage() {{
    let position = 0
    let index = 0

    while (index < IMAGE_RLE.length) {{
        const count = IMAGE_RLE[index]
        const colour = IMAGE_RLE[index + 1]

        if (colour != 0) {{
            let ink = inkybit.Color.Black
            if (colour == 2) {{
                ink = inkybit.Color.Accent
            }}

            for (let offset = 0; offset < count; offset++) {{
                const pixel = position + offset
                inkybit.setPixel(pixel % WIDTH, Math.idiv(pixel, WIDTH), ink)
            }}
        }}

        position += count
        index += 2
    }}
}}

inkybit.clear()
drawRleImage()
inkybit.show()
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--diameter", type=int, default=50)
    parser.add_argument("--png", type=Path, default=Path("black_circle_50.png"))
    parser.add_argument("--ts", type=Path, default=Path("makecode_project/main.ts"))
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    pixels = make_pixels(args.diameter)
    encoded = rle_encode(pixels)

    write_png(args.png, pixels)
    args.ts.write_text(makecode_ts(encoded, args.png), encoding="utf-8")

    raw_pixels = WIDTH * HEIGHT
    print(f"PNG: {args.png}")
    print(f"MakeCode TS: {args.ts}")
    print(f"RLE pairs: {len(encoded) // 2}")
    print(f"RLE values: {len(encoded)} ({len(encoded) / raw_pixels:.1%} of raw pixels)")


if __name__ == "__main__":
    main()
